### ISSUE TITLE
Stream audio - audio still muted while recording

### ISSUE THREAD

**Issue by nkay08** [brian-girko/desktop-screen-record#1]
Hey, first of all thanks you for this nice extension.

However, audio is muted when recording. For my purposes I need to hear the audio while recording. There is an option "Stream audio" that is supposed to provide this functionality, but when activated the audio still mutes when recording.

Kind regards.

**Comment by brian-girko** [comment]
Are you trying to record a browser tab? What is your OS?

**Comment by nkay08** [comment]
Thank you for the quick reaction. I'm trying to use the extension on Windows (could try it on a Linux as well). I tried it in Chrome and in Edge, with the same results.
I want to record my entire screen and record system sound. When the browser screen sharing menu opens, I select a screen and activate the "Share audio" option.

By the way, does "System audio" source include my own microphone or are these mutually exclusive?
If they are mutually exclusive, I'd have the feature request of an option (checkbox) to add optionally add microphone to another audio source.

**Comment by brian-girko** [comment]
Try 0.2.2 release

**Comment by nkay08** [comment]
Very nice!
Your changes have fixed this issue on my end.

Again, thank you for your extension and your help.
